trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Images to build
strategy:
  matrix:
    bmi_1:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-ubuntu
      SPACK_INSTALL_SPEC: netcdf@4.1.3%gcc@7 ^hdf5@:1.8.12%gcc@7
      TAG:                ubuntu-gcc7-netcdf4.1.3
    bmi_2:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-ubuntu
      SPACK_INSTALL_SPEC: netcdf@4.2.1%gcc@4 netcdf-fortran@4.4.5%gcc@4 netcdf@4.2.1%gcc@5 netcdf-fortran@4.4.5%gcc@5 netcdf@4.2.1%gcc@6 netcdf-fortran@4.4.5%gcc@6 netcdf@4.2.1%gcc@7 netcdf-fortran@4.4.5%gcc@7 netcdf@4.2.1%gcc@8 netcdf-fortran@4.4.5%gcc@8 netcdf@4.2.1%gcc@9 netcdf-fortran@4.4.5%gcc@9
      TAG:                ubuntu-gcc-netcdf4.2.1-netcdff4.4.5
    bmi_3:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-centos
      SPACK_INSTALL_SPEC: netcdf@4.7.1 netcdf-fortran@4.5.2
      TAG:                centos-gcc4-netcdf4.7.1-netcdf-4.5.2
    bmi_4:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-centos
      SPACK_INSTALL_SPEC: esmf ^mvapich2
      TAG:                centos-gcc4-mvapich2-esmf
    bmi_5:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-ubuntu
      SPACK_INSTALL_SPEC: esmf%gcc@8 ^mpich%gcc@8
      TAG:                ubuntu-gcc8-mpich-esmf
    bmi_6:
      BASE_IMAGE:         liambindle/build-matrix-images-base:19.09-ubuntu
      SPACK_INSTALL_SPEC: esmf%gcc@4 ^openmpi%gcc@4 esmf%gcc@5 ^openmpi%gcc@5 esmf%gcc@6 ^openmpi%gcc@6 esmf%gcc@7 ^openmpi%gcc@7 esmf%gcc@8 ^openmpi%gcc@8 esmf%gcc@9 ^openmpi%gcc@9
      TAG:                ubuntu-gcc-openmpi-esmf

# Steps to build images
steps:
- script: |
    printf "##vso[task.setvariable variable=DATE_TAG;]%s\n" $(date "+%g.%m")
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: liambindle/build-matrix-images
    tags: $(DATE_TAG)-$(TAG)
    arguments: |
      --build-arg BASE_IMAGE=$(BASE_IMAGE)
      --build-arg SPACK_INSTALL_SPEC="$(SPACK_INSTALL_SPEC)"
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub
    repository: liambindle/build-matrix-images
    command: push
    tags: |
      $(DATE_TAG)-$(TAG)